version: "3"
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure
